# Generated by Django 2.1.4 on 2019-01-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formularios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoFormulario', models.CharField(max_length=60)),
                ('detalle', models.CharField(help_text='Texto de no mas de 200 caracteres', max_length=200)),
                ('formulario', models.TextField()),
            ],
        ),
    ]
