# Generated by Django 2.1.4 on 2019-01-03 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SRI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formularios',
        ),
    ]
