# Generated by Django 2.1.4 on 2019-01-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRI', '0003_formularios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularios',
            name='detalle',
            field=models.TextField(),
        ),
    ]
