# Generated by Django 2.1.4 on 2019-01-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRI', '0004_auto_20190102_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularios',
            name='codigo_version_formulario',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
