# Generated by Django 2.1.4 on 2019-01-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SRI', '0008_f104a_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='f104a',
            options={'verbose_name_plural': 'FORMULARIO 104A - IVA MENSUAL PERSONAS NO OBLIGADAS A LLEVAR CONTABILIDAD'},
        ),
    ]
