# Generated by Django 2.0 on 2019-01-11 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0031_items_nuevo'),
        ('SRI', '0009_auto_20190110_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='F104',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_version_formulario', models.CharField(max_length=60)),
                ('ruc', models.CharField(max_length=60)),
                ('codigoMoneda', models.CharField(default='1', max_length=20)),
                ('c101', models.CharField(blank=True, max_length=60, null=True)),
                ('c102', models.CharField(blank=True, max_length=60, null=True)),
                ('c31', models.CharField(max_length=60)),
                ('c104', models.CharField(blank=True, max_length=60, null=True)),
                ('c201', models.CharField(blank=True, max_length=60, null=True)),
                ('c202', models.CharField(blank=True, max_length=60, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa')),
            ],
        ),
    ]
