# Generated by Django 2.0 on 2018-10-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0002_producto_detalles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='detalles',
        ),
        migrations.AddField(
            model_name='detalleproproveedor',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
