# Generated by Django 2.0 on 2018-11-07 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0003_auto_20181007_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproproveedor',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.Proveedor'),
        ),
    ]
