# Generated by Django 2.0 on 2018-12-13 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0009_remove_funciones_empresa'),
        ('INVENTARIO', '0004_auto_20181107_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa'),
        ),
        migrations.AddField(
            model_name='kardex',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa'),
        ),
    ]
