# Generated by Django 2.0 on 2018-12-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0005_auto_20181213_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcas',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
