# Generated by Django 2.0 on 2018-12-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0006_auto_20181214_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='kardex',
            name='empresa',
        ),
    ]
