# Generated by Django 2.0 on 2018-12-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0007_auto_20181214_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='medida',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
