# Generated by Django 2.0 on 2019-01-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0008_auto_20181228_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproproveedor',
            name='icepvp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detalleproproveedor',
            name='irbpnr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detalleproproveedor',
            name='irbpnrpvp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detalleproproveedor',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detalleproproveedor',
            name='ivapvp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detalleproproveedor',
            name='porcentajeGanancia',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detalleproproveedor',
            name='porcentajeICE',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detalleproproveedor',
            name='porcentajeIRBPNR',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detalleproproveedor',
            name='porcentajeIVA',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detalleproproveedor',
            name='precioProveedor',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detalleproproveedor',
            name='pvp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detalleproproveedor',
            name='recargo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detalleproproveedor',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detalleproproveedor',
            name='totalpvp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
