# Generated by Django 2.0 on 2019-02-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTARIO', '0012_compra_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='stockmax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kardex',
            name='stockmin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
