# Generated by Django 2.0 on 2019-02-14 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0031_items_nuevo'),
        ('INVENTARIO', '0013_auto_20190214_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa'),
        ),
    ]
