# Generated by Django 2.0 on 2018-10-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0002_myusuario_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusuario',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
