# Generated by Django 2.0 on 2018-12-31 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('USERS', '0003_myusuario_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('destino', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERS.myUsuario')),
            ],
        ),
    ]
