# Generated by Django 2.0 on 2018-12-31 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0003_myusuario_is_admin'),
        ('NOTIFICACIONES', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mensajes',
            name='usuario',
        ),
        migrations.AddField(
            model_name='mensajes',
            name='origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='USERS.myUsuario'),
        ),
        migrations.AddField(
            model_name='mensajes',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NOTIFICACIONES.Mensajes'),
        ),
        migrations.AddField(
            model_name='mensajes',
            name='prioridad',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
