# Generated by Django 2.0 on 2018-12-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOTIFICACIONES', '0002_auto_20181230_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='asunto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
