# Generated by Django 2.1.4 on 2019-01-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOTIFICACIONES', '0005_mensajeschat_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mensajeschat',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
