# Generated by Django 2.0 on 2018-10-06 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TALENTO_HUMANO', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnticiposSueldos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('descripcion', models.TextField()),
                ('empleado', models.ForeignKey(on_delete=True, to='TALENTO_HUMANO.Empleado')),
            ],
            options={
                'verbose_name_plural': '4. Anticipo de Sueldos',
            },
        ),
        migrations.CreateModel(
            name='AperturaCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, unique=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('totalBilletes', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('totalMonedas', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('totalDocumentos', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('saldoInicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '1. Apertura de Caja',
            },
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, unique=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('saldoInicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('totalGasto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('totalVentas', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('totalDiario', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('totalBilletes', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('totalMonedas', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('totalDocumentos', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('saldoFinal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('faltante', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '3. Cierre de Caja',
            },
        ),
        migrations.CreateModel(
            name='GastosDiarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('tipoDocumento', models.CharField(default='FACTURA DE LA CASA COMERCIAL', max_length=60)),
                ('numeroDocumento', models.CharField(default='000-000-000000000', max_length=20)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '2. Registro de Gastos Diarios',
            },
        ),
    ]
