# Generated by Django 2.0 on 2018-10-10 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CARTERA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturacaja',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
