# Generated by Django 2.0 on 2018-10-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARTERA', '0003_auto_20181010_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrecaja',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
