# Generated by Django 2.0 on 2018-10-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARTERA', '0004_auto_20181010_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturacaja',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
