# Generated by Django 2.0 on 2018-10-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARTERA', '0005_aperturacaja_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
