# Generated by Django 2.0 on 2018-10-13 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CARTERA', '0006_cierrecaja_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cierrecaja',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='gastosdiarios',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CARTERA.AperturaCaja'),
        ),
        migrations.AddField(
            model_name='gastosdiarios',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CARTERA.AperturaCaja'),
        ),
    ]
