# Generated by Django 2.0 on 2018-11-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARTERA', '0009_auto_20181103_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='cuentasCobrar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
