# Generated by Django 2.0 on 2018-12-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CARTERA', '0010_cierrecaja_cuentascobrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturacaja',
            name='bil1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='aperturacaja',
            name='bil10',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='aperturacaja',
            name='bil100',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='aperturacaja',
            name='bil20',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='aperturacaja',
            name='bil5',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='aperturacaja',
            name='bil50',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='aperturacaja',
            name='mon1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='aperturacaja',
            name='mon10',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='aperturacaja',
            name='mon100',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='aperturacaja',
            name='mon25',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='aperturacaja',
            name='mon5',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='aperturacaja',
            name='mon50',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
