# Generated by Django 2.1.4 on 2019-01-05 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0031_items_nuevo'),
        ('CARTERA', '0011_auto_20181221_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturacaja',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa'),
        ),
    ]
