# Generated by Django 2.0 on 2018-10-06 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '3. Cargos del Departamento',
            },
        ),
        migrations.CreateModel(
            name='DatosEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=100)),
                ('nombreComercial', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=13)),
                ('obligado_llevar_contabilidad', models.BooleanField(default=True)),
                ('contribuyenteEspecial', models.BooleanField(default=False)),
                ('contribuyenteEspecialNumero', models.CharField(blank=True, max_length=10, null=True)),
                ('direccionMatriz', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('convencional', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=60)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Logo')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '1. Datos de la Empresa',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa')),
            ],
            options={
                'verbose_name_plural': '2. Departamentos de la Empresa',
            },
        ),
        migrations.CreateModel(
            name='Funciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '5. Funciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa')),
            ],
            options={
                'verbose_name_plural': '4. Grupos Organizacionales',
            },
        ),
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.Lugares')),
            ],
            options={
                'verbose_name_plural': '0. Paises, Provincias, Ciudades, Parroquias',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.Funciones')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.Grupo')),
            ],
            options={
                'verbose_name_plural': '6. Permisos',
            },
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_texto', models.CharField(default='#000000', max_length=12)),
                ('color_fondo', models.CharField(default='#FFFFFF', max_length=12)),
                ('color_lineas', models.CharField(default='#0B3B2E', max_length=12)),
                ('color_encabezados_tablas', models.CharField(default='#0B3B2E', max_length=12)),
                ('color_encabezados_tablas_texto', models.CharField(default='#0B3B2E', max_length=12)),
                ('encabezado', models.ImageField(blank=True, null=True, upload_to='reportes/encabezado')),
                ('ruta_imagenes', models.CharField(default='http://localhost:8000/', max_length=120)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa')),
            ],
            options={
                'verbose_name_plural': '7. Configuraciones del Reporte',
            },
        ),
        migrations.AddField(
            model_name='datosempresa',
            name='parroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.Lugares'),
        ),
        migrations.AddField(
            model_name='datosempresa',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargos',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.Departamento'),
        ),
    ]
