# Generated by Django 2.0 on 2018-10-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugares',
            name='ciudad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lugares',
            name='pais',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lugares',
            name='parroquia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lugares',
            name='provincia',
            field=models.BooleanField(default=False),
        ),
    ]
