# Generated by Django 2.0 on 2018-11-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0003_auto_20181006_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='color_encabezados_tablas',
            field=models.CharField(default='#0B3B2E', max_length=50),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='color_encabezados_tablas_texto',
            field=models.CharField(default='#0B3B2E', max_length=50),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='color_fondo',
            field=models.CharField(default='#FFFFFF', max_length=50),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='color_lineas',
            field=models.CharField(default='#0B3B2E', max_length=50),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='color_texto',
            field=models.CharField(default='#000000', max_length=50),
        ),
    ]
