# Generated by Django 2.0 on 2018-11-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0004_auto_20181104_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosempresa',
            name='nombreComercial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datosempresa',
            name='razonSocial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
