# Generated by Django 2.0 on 2018-11-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0005_auto_20181107_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosempresa',
            name='convencional',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datosempresa',
            name='direccionMatriz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datosempresa',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='datosempresa',
            name='obligado_llevar_contabilidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datosempresa',
            name='ruc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='datosempresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
