# Generated by Django 2.0 on 2018-12-13 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0007_cargos_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='funciones',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa'),
        ),
    ]
