# Generated by Django 2.0 on 2018-12-13 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0008_auto_20181213_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funciones',
            name='empresa',
        ),
    ]
