# Generated by Django 2.0 on 2018-12-14 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0010_remove_departamento_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='empresa',
        ),
        migrations.AddField(
            model_name='departamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa'),
        ),
    ]
