# Generated by Django 2.0 on 2018-12-21 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0014_remove_permiso_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.Items'),
        ),
    ]
