# Generated by Django 2.0 on 2018-12-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0015_permiso_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='funcion',
        ),
    ]
