# Generated by Django 2.0 on 2018-12-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0016_remove_permiso_funcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='funciones',
            name='icono',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
