# Generated by Django 2.0 on 2018-12-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0017_funciones_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='enlace',
            field=models.CharField(default='', max_length=100),
        ),
    ]
