# Generated by Django 2.0 on 2018-12-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0019_auto_20181221_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funciones',
            name='icono',
        ),
        migrations.AlterField(
            model_name='items',
            name='enlace',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
