# Generated by Django 2.0 on 2018-12-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0020_auto_20181221_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='funciones',
            name='icono',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
