# Generated by Django 2.0 on 2018-12-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0021_funciones_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='funciones',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
