# Generated by Django 2.0 on 2018-12-23 15:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0023_helpers_helpersdetalles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpersdetalles',
            name='detalles',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
