# Generated by Django 2.0 on 2018-12-23 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0024_auto_20181223_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpersdetalles',
            name='helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.Helpers'),
        ),
    ]
