# Generated by Django 2.0 on 2018-12-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0025_helpersdetalles_helper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpersdetalles',
            name='subtitulo',
        ),
    ]
