# Generated by Django 2.0 on 2018-12-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0026_remove_helpersdetalles_subtitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpersdetalles',
            name='tituloGeneral',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
