# Generated by Django 2.0 on 2018-12-23 18:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0027_helpersdetalles_titulogeneral'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpers',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
