# Generated by Django 2.0 on 2018-12-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0030_items_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='nuevo',
            field=models.BooleanField(default=False),
        ),
    ]
