# Generated by Django 2.0 on 2019-07-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0031_items_nuevo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosempresa',
            options={},
        ),
    ]
