# Generated by Django 2.0 on 2018-11-10 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CONTABILIDAD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancuentas',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONTABILIDAD.PlanCuentas'),
        ),
    ]
