# Generated by Django 2.0 on 2018-11-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONTABILIDAD', '0002_plancuentas_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancuentas',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
