# Generated by Django 2.0 on 2018-11-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONTABILIDAD', '0004_plancuentas_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancuentas',
            name='nombre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
