# Generated by Django 2.0 on 2018-12-25 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0029_helpers_horafecha'),
        ('CONTABILIDAD', '0006_bancos_cuenta_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta_banco',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa'),
        ),
    ]
