# Generated by Django 2.0 on 2018-12-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONTABILIDAD', '0007_cuenta_banco_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta_banco',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
