# Generated by Django 2.0 on 2018-12-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONTABILIDAD', '0008_cuenta_banco_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta_banco',
            name='tipo_cuenta',
            field=models.CharField(choices=[('CA', 'AHORRO'), ('CC', 'CORRIENTE')], max_length=50),
        ),
    ]
