# Generated by Django 2.0 on 2018-12-26 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CONTABILIDAD', '0009_auto_20181225_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceCuentaBancos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CONTABILIDAD.Cuenta_Banco')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CONTABILIDAD.PlanCuentas')),
            ],
        ),
    ]
