# Generated by Django 2.0 on 2018-12-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONTABILIDAD', '0010_enlacecuentabancos'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlacecuentabancos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
