# Generated by Django 2.0 on 2018-12-27 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CARTERA', '0011_auto_20181221_1442'),
        ('CONTABILIDAD', '0011_enlacecuentabancos_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceCuentaCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CARTERA.AperturaCaja')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CONTABILIDAD.PlanCuentas')),
            ],
        ),
    ]
