# Generated by Django 2.0 on 2018-10-06 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CLIENTES', '0001_initial'),
        ('CONFIGURACION', '0001_initial'),
        ('TRANSPORTE', '0001_initial'),
        ('USERS', '0001_initial'),
        ('INVENTARIO', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigosEstablecimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Codigo de 3 digitos', max_length=3)),
                ('estado', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa')),
            ],
            options={
                'verbose_name_plural': '2. Codigo de Establecimientos',
            },
        ),
        migrations.CreateModel(
            name='DatosDocumentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoEmision', models.CharField(default='1', max_length=1)),
                ('firmaElectronica', models.FileField(blank=True, null=True, upload_to='firmas')),
                ('claveFirma', models.CharField(max_length=30)),
                ('banner', models.FileField(blank=True, null=True, upload_to='Banner')),
                ('secuencial', models.IntegerField(default=1)),
                ('secuencialGuias', models.IntegerField(default=1)),
                ('secuencialRetencion', models.IntegerField(default=1)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '5. Datos de los Documentos',
            },
        ),
        migrations.CreateModel(
            name='DetallesFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('subtotal_0', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('subtotal_iva', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('ice', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('irbpnr', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('codigo_iva', models.CharField(default=0, max_length=30)),
                ('tarifa_iva', models.CharField(default=0, max_length=30)),
                ('codigo_ice', models.CharField(default=0, max_length=30)),
                ('tarifa_ice', models.CharField(default=0, max_length=30)),
                ('codigo_irbpnr', models.CharField(default=0, max_length=30)),
                ('tarifa_irbpnr', models.CharField(default=0, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DetallesRetencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('impuesto', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('baseImp', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total_retencion', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoComprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('siglas', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '9. Estado de Comprobantes',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contado', models.BooleanField(default=True)),
                ('diasPlazo', models.IntegerField(default=0)),
                ('ambiente', models.IntegerField(default=1)),
                ('secuencial', models.CharField(blank=True, max_length=9, null=True, unique='True')),
                ('codigoEstablecimiento', models.CharField(blank=True, default='001', max_length=3, null=True)),
                ('puntoEmision', models.CharField(blank=True, default='001', max_length=3, null=True)),
                ('tipo', models.CharField(choices=[('FACTURA', 'FACTURA'), ('PROFORMA', 'PROFORMA')], max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('subtotal_0', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('subtotal_iva', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('ice', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('irbpnr', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('clave_acceso', models.CharField(max_length=50)),
                ('guiaRemision', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CLIENTES.Cliente')),
                ('datosFactura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOCUMENTOS_ELECTRONICOS.DatosDocumentos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuiaRemision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencial', models.CharField(blank=True, max_length=9, null=True, unique='True')),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('puntoPartida', models.CharField(blank=True, max_length=120, null=True)),
                ('fachaIniTrans', models.DateField()),
                ('fachaFinTrans', models.DateField()),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('motivoTraslado', models.CharField(blank=True, max_length=200, null=True)),
                ('puntoLLegada', models.CharField(blank=True, max_length=200, null=True)),
                ('docAduanero', models.CharField(blank=True, max_length=100, null=True)),
                ('codEstablecimiento', models.CharField(blank=True, max_length=10, null=True)),
                ('ruta', models.CharField(blank=True, max_length=200, null=True)),
                ('clave_acceso', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
                ('datosGuia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOCUMENTOS_ELECTRONICOS.DatosDocumentos')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOCUMENTOS_ELECTRONICOS.Factura')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TRANSPORTE.VehiculoTrans')),
            ],
        ),
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('codigo', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': '6. Impuestos',
            },
        ),
        migrations.CreateModel(
            name='PuntoEmision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Codigo de 3 digitos', max_length=3)),
                ('estado', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa')),
            ],
            options={
                'verbose_name_plural': '3. Punto de Emision',
            },
        ),
        migrations.CreateModel(
            name='Retencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('secuencial', models.CharField(blank=True, max_length=9, null=True, unique='True')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('clave_acceso', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.Compra')),
                ('datosRetencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOCUMENTOS_ELECTRONICOS.DatosDocumentos')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.Proveedor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='USERS.myUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tarifas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('numeroCampo', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('detalle', models.TextField()),
                ('tarifaAD', models.CharField(blank=True, max_length=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usado_en_retencion', models.BooleanField(default=False)),
                ('valorIva', models.BooleanField(default=False)),
                ('impuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOCUMENTOS_ELECTRONICOS.Impuestos')),
            ],
            options={
                'verbose_name_plural': '6.1. Tarifas',
            },
        ),
        migrations.CreateModel(
            name='TipoAmbiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('codigo', models.CharField(max_length=3)),
                ('estado', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa')),
            ],
            options={
                'verbose_name_plural': '1. Ambientes',
            },
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': '8. Tipo de Comprobantes',
            },
        ),
        migrations.CreateModel(
            name='TipoEmision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('codigo', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': '4. Tipo Emision',
            },
        ),
        migrations.AddField(
            model_name='detallesretencion',
            name='retencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DOCUMENTOS_ELECTRONICOS.Retencion'),
        ),
        migrations.AddField(
            model_name='detallesretencion',
            name='tarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOCUMENTOS_ELECTRONICOS.Tarifas'),
        ),
        migrations.AddField(
            model_name='detallesfactura',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOCUMENTOS_ELECTRONICOS.Factura'),
        ),
        migrations.AddField(
            model_name='detallesfactura',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='INVENTARIO.DetalleProProveedor'),
        ),
        migrations.AddField(
            model_name='datosdocumentos',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOCUMENTOS_ELECTRONICOS.TipoAmbiente'),
        ),
        migrations.AddField(
            model_name='datosdocumentos',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa'),
        ),
    ]
