# Generated by Django 2.0 on 2018-10-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='secuencial',
            field=models.CharField(blank=True, max_length=15, null=True, unique='True'),
        ),
    ]
