# Generated by Django 2.0 on 2018-10-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0003_datosdocumentos_secuenciaproforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosdocumentos',
            name='caducidadProforma',
            field=models.TextField(default='Estos precios pueden variar; válido por 7 dias a partir de la emisión..!!'),
        ),
    ]
