# Generated by Django 2.0 on 2018-10-11 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0004_datosdocumentos_caducidadproforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosdocumentos',
            name='codigoEstablecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOCUMENTOS_ELECTRONICOS.CodigosEstablecimientos'),
        ),
        migrations.AddField(
            model_name='datosdocumentos',
            name='puntoEmision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOCUMENTOS_ELECTRONICOS.PuntoEmision'),
        ),
    ]
