# Generated by Django 2.0 on 2018-10-11 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0005_auto_20181011_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoambiente',
            name='empresa',
        ),
    ]
