# Generated by Django 2.0 on 2018-10-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CARTERA', '0007_auto_20181013_1139'),
        ('DOCUMENTOS_ELECTRONICOS', '0006_remove_tipoambiente_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CARTERA.AperturaCaja'),
        ),
    ]
