# Generated by Django 2.0 on 2018-11-03 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0003_myusuario_is_admin'),
        ('DOCUMENTOS_ELECTRONICOS', '0007_factura_caja'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentasPorCobrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('plazo', models.IntegerField(default=0, help_text='dias de plazo')),
                ('cuotas', models.IntegerField(default=1)),
                ('estado', models.BooleanField(default=False)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DOCUMENTOS_ELECTRONICOS.Factura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERS.myUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesCuentasCobrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_esperada', models.DateField()),
                ('fecha_pago', models.DateField()),
                ('abono', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('estado', models.BooleanField(default=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DOCUMENTOS_ELECTRONICOS.CuentasPorCobrar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERS.myUsuario')),
            ],
        ),
    ]
