# Generated by Django 2.0 on 2018-11-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0008_cuentasporcobrar_detallescuentascobrar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentasporcobrar',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
