# Generated by Django 2.0 on 2018-11-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0010_auto_20181103_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallescuentascobrar',
            name='n_pago',
            field=models.IntegerField(default=1),
        ),
    ]
