# Generated by Django 2.0 on 2018-11-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0011_detallescuentascobrar_n_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallescuentascobrar',
            name='fecha_pago',
            field=models.DateField(auto_now_add=True),
        ),
    ]
