# Generated by Django 2.0 on 2018-11-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0012_auto_20181103_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallescuentascobrar',
            name='detalles',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
