# Generated by Django 2.0 on 2018-11-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0013_detallescuentascobrar_detalles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallescuentascobrar',
            name='fecha_pago',
            field=models.DateField(),
        ),
    ]
