# Generated by Django 2.0 on 2018-11-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0014_auto_20181103_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallescuentascobrar',
            name='fecha_esperada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
