# Generated by Django 2.0 on 2018-11-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0015_auto_20181103_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallescuentascobrar',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
