# Generated by Django 2.0 on 2018-11-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0016_auto_20181103_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallescuentascobrar',
            name='usuario',
        ),
    ]
