# Generated by Django 2.0 on 2018-11-04 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0017_remove_detallescuentascobrar_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentasporcobrar',
            name='factura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DOCUMENTOS_ELECTRONICOS.Factura'),
        ),
    ]
