# Generated by Django 2.0 on 2018-11-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CARTERA', '0009_auto_20181103_1211'),
        ('DOCUMENTOS_ELECTRONICOS', '0018_auto_20181104_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallescuentascobrar',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CARTERA.AperturaCaja'),
        ),
    ]
