# Generated by Django 2.0 on 2018-11-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0019_detallescuentascobrar_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallescuentascobrar',
            name='nrecibo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
