# Generated by Django 2.0 on 2018-11-05 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0004_auto_20181104_1226'),
        ('DOCUMENTOS_ELECTRONICOS', '0020_detallescuentascobrar_nrecibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallescuentascobrar',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa'),
        ),
    ]
