# Generated by Django 2.0 on 2018-11-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0022_remove_detallescuentascobrar_nrecibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado_por_pagar',
            field=models.BooleanField(default=True),
        ),
    ]
