# Generated by Django 2.0 on 2018-11-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0023_factura_estado_por_pagar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado_por_pagar',
            field=models.BooleanField(default=False),
        ),
    ]
