# Generated by Django 2.0 on 2018-12-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0026_guiaremision_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaremision',
            name='ambiente',
            field=models.IntegerField(default=1),
        ),
    ]
