# Generated by Django 2.0 on 2018-12-13 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0009_remove_funciones_empresa'),
        ('DOCUMENTOS_ELECTRONICOS', '0027_guiaremision_ambiente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallescuentascobrar',
            name='empresa',
        ),
        migrations.AddField(
            model_name='cuentasporcobrar',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa'),
        ),
        migrations.AddField(
            model_name='factura',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa'),
        ),
        migrations.AddField(
            model_name='retencion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa'),
        ),
    ]
