# Generated by Django 2.0 on 2018-12-13 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0028_auto_20181213_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name_plural': '10. Facturacion'},
        ),
        migrations.AlterModelOptions(
            name='guiaremision',
            options={'verbose_name_plural': '11. Guias de Remision'},
        ),
        migrations.AlterModelOptions(
            name='retencion',
            options={'verbose_name_plural': '12. Retenciones'},
        ),
    ]
