# Generated by Django 2.0 on 2018-12-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0029_auto_20181213_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='empresa',
        ),
    ]
