# Generated by Django 2.0 on 2018-12-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0009_remove_funciones_empresa'),
        ('DOCUMENTOS_ELECTRONICOS', '0030_remove_factura_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa'),
        ),
    ]
