# Generated by Django 2.0 on 2018-12-14 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0031_factura_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='empresa',
        ),
    ]
