# Generated by Django 2.0 on 2018-12-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0032_remove_factura_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guiaremision',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='retencion',
            name='empresa',
        ),
    ]
