# Generated by Django 2.0 on 2018-12-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0033_auto_20181214_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentasporcobrar',
            name='empresa',
        ),
    ]
