# Generated by Django 2.0 on 2018-12-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0034_remove_cuentasporcobrar_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='secuencial',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
