# Generated by Django 2.0 on 2018-12-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0036_guiaremision_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiaremision',
            name='ambiente',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
