# Generated by Django 2.0 on 2018-12-23 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0029_helpers_horafecha'),
        ('DOCUMENTOS_ELECTRONICOS', '0038_auto_20181223_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='empresa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa'),
        ),
    ]
