# Generated by Django 2.0 on 2018-12-23 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0029_helpers_horafecha'),
        ('DOCUMENTOS_ELECTRONICOS', '0039_factura_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='retencion',
            name='empresa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa'),
        ),
    ]
