# Generated by Django 2.0 on 2018-12-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0041_retencion_ambiente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesretencion',
            name='codigo',
        ),
    ]
