# Generated by Django 2.0 on 2018-12-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0042_remove_detallesretencion_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesretencion',
            name='docSustento',
            field=models.CharField(blank=True, default='001001000000001', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='detallesretencion',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
