# Generated by Django 2.0 on 2018-12-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0043_auto_20181224_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='retencion',
            name='fecha_emisionFactura',
            field=models.DateField(blank=True, null=True),
        ),
    ]
