# Generated by Django 2.0 on 2018-12-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0044_retencion_fecha_emisionfactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifas',
            name='codigo',
            field=models.IntegerField(default=0),
        ),
    ]
