# Generated by Django 2.0 on 2018-12-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0045_auto_20181228_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaremision',
            name='tipo',
            field=models.CharField(default='GUIA_REMISION', max_length=20),
        ),
        migrations.AddField(
            model_name='retencion',
            name='tipo',
            field=models.CharField(default='RETENCION', max_length=20),
        ),
    ]
