# Generated by Django 2.0 on 2018-12-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0047_auto_20181229_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='clave_acceso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
