# Generated by Django 2.0 on 2018-12-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0049_auto_20181229_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuestos',
            name='codigo',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
