# Generated by Django 2.0 on 2019-02-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0050_auto_20181231_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retencion',
            name='secuencial',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
