# Generated by Django 2.0 on 2019-07-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCUMENTOS_ELECTRONICOS', '0051_auto_20190206_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
