# Generated by Django 2.0 on 2018-10-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLIENTES', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombreComercial',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
