# Generated by Django 2.0 on 2018-10-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLIENTES', '0002_cliente_nombrecomercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(max_length=13),
        ),
    ]
