# Generated by Django 2.0 on 2018-10-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CLIENTES', '0003_auto_20181027_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombreComercial',
        ),
    ]
