# Generated by Django 2.0 on 2019-01-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLIENTES', '0004_remove_cliente_nombrecomercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=50),
        ),
    ]
