# Generated by Django 2.0 on 2018-10-06 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CONFIGURACION', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=4)),
                ('sueldoBasico', models.DecimalField(decimal_places=2, default=368.0, max_digits=9)),
                ('diasLaborables', models.IntegerField(default=360)),
                ('diasMensuales', models.IntegerField(default=30)),
                ('horasmensuales', models.IntegerField(default=200)),
                ('horassemanales', models.IntegerField(default=40)),
                ('horasdiarias', models.IntegerField(default=8)),
                ('activado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=120)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=20, null=True)),
                ('cargas', models.CharField(max_length=2)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('observaciones', models.CharField(blank=True, max_length=300, null=True)),
                ('fechaIngreso', models.DateField(blank=True, null=True)),
                ('fechaSalida', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.Departamento')),
                ('parroquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.Lugares')),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formaPago', models.CharField(default='EFECTIVO', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='IngresosEgresos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('I', 'INGRESO'), ('E', 'EGRESO')], max_length=1)),
                ('nombre', models.CharField(max_length=60)),
                ('formula', models.CharField(blank=True, default='0', max_length=150, null=True)),
                ('campo', models.CharField(blank=True, max_length=60, null=True)),
                ('atributo', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('prioridad', models.IntegerField(default=0)),
                ('decimales', models.IntegerField(default=2)),
                ('tipo_campo', models.CharField(choices=[('text', 'text'), ('number', 'number')], default='number', max_length=20)),
                ('es_calculable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remuneraciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(blank=True, max_length=30, null=True)),
                ('dias', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('sueldoInicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('mes', models.CharField(default='00', max_length=2)),
                ('xiiisueldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('xivsueldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('fondosreserva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('vacaciones', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('otrosingresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('horasextras', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('totalIngresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('aporteiess', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iece', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('prestamosiess', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('impuestoalarenta', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('anticiposueldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('multas', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('otrosegresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('totalEgresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='RolPagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroRol', models.CharField(max_length=10)),
                ('fechaRol', models.DateField(auto_now_add=True)),
                ('PeridoRol', models.CharField(max_length=20)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa')),
            ],
        ),
        migrations.CreateModel(
            name='Sueldos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('diasTrabajados', models.IntegerField(default=30)),
                ('horasdiarias', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('totalHoras', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('valor_hora', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('estado', models.BooleanField(default=True)),
                ('beneficio', models.BooleanField(default=False)),
                ('annio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TALENTO_HUMANO.Anio')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.Cargos')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TALENTO_HUMANO.Empleado')),
                ('formaPago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TALENTO_HUMANO.FormaPago')),
            ],
        ),
        migrations.AddField(
            model_name='remuneraciones',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TALENTO_HUMANO.RolPagos'),
        ),
        migrations.AddField(
            model_name='remuneraciones',
            name='sueldo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TALENTO_HUMANO.Sueldos'),
        ),
    ]
