# Generated by Django 2.0 on 2018-10-23 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CONFIGURACION', '0003_auto_20181006_2113'),
        ('TALENTO_HUMANO', '0002_auto_20181008_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='anio',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa'),
        ),
    ]
