# Generated by Django 2.0 on 2018-11-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TALENTO_HUMANO', '0003_anio_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anio',
            name='anio',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
