# Generated by Django 2.0 on 2018-11-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TALENTO_HUMANO', '0004_auto_20181110_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='anio',
            name='diasSemanales',
            field=models.IntegerField(default=5),
        ),
    ]
