# Generated by Django 2.0 on 2018-12-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TALENTO_HUMANO', '0005_anio_diassemanales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anio',
            name='anio',
            field=models.CharField(max_length=4),
        ),
    ]
