# Generated by Django 2.0 on 2018-10-06 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CLIENTES', '0001_initial'),
        ('CONFIGURACION', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductorTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(blank=True, max_length=13, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('licencia', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '2. Registro de Conductores',
            },
        ),
        migrations.CreateModel(
            name='EmpresaTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(blank=True, max_length=13, null=True)),
                ('razonSocial', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=100)),
                ('convencional', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CONFIGURACION.DatosEmpresa')),
            ],
            options={
                'verbose_name_plural': '1. Empresas de Transporte',
            },
        ),
        migrations.CreateModel(
            name='VehiculoTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoAdicional', models.CharField(blank=True, max_length=20, null=True)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TRANSPORTE.ConductorTrans')),
            ],
            options={
                'verbose_name_plural': '3. Registro de Vehiculos',
            },
        ),
        migrations.AddField(
            model_name='conductortrans',
            name='empresaTrans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRANSPORTE.EmpresaTransporte'),
        ),
        migrations.AddField(
            model_name='conductortrans',
            name='tipoIndentificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CLIENTES.TipoIndentificacion'),
        ),
    ]
